### ISSUE TITLE
Issue when embedding via WYSIWYG

### ISSUE THREAD

**Issue by stooit** [govCMS/govcms-ckan#37] opened 2016-04-27 06:25 UTC
Initial save on content embedded via Media (in WYSIWYG) appears to work as expected, however subsequent saves strip the embed (or turn it into a link).

Could be a govCMS WYSIWYG profile configuration issue, but adding here to track.

**Comment by gollyg** [comment] 2016-04-27 13:47
Had a similar issue with oEmbed module. It is possible to switch out the rendering based upon WYSIWG preview. From memory it will drop the media token if it does not have an appropriate wrapper (I think it required a span or div).

**Comment by seanhamlin** [comment] 2017-02-22 22:20
Closing as a duplicate of https://github.com/govCMS/govcms-ckan/issues/38

**Closed as completed by seanhamlin** 2017-02-22 22:20 UTC
Labels: bug
